travis:
  secure:
    BINSTAR_TOKEN: brQQTCQebTQzf5Zoo/dYL5fGA3NqMWh3RK4+bBQsnRyplN2sT5aFt/GVM44/ezUUOHgezT1H87Sq4apW7ok8fpQqwU4F2YHig9M/kkT1zaAaAbAvl8DbtaPMLFstaCR4fKftXN4ULEqcPwb1qrO2dMhkZM6eA0E6RXg7BPwZu1tF/zo1UIfFIRDzN33z/uIjyuY/DnpQMc4N7JzblOvA+ndv+1Jy/ZGy+/lAgTeg4rbroVlE3x5zCYJKxyKo5kaZZC1azoCB+YoFMhYLNrGGPYO5is8sYuiCghCMGMrhVIkpSNfuHvPZihNKOhS+w2Abp169OKFeo6LfAiWKTVKxV9Jfvm+hz2d162KgMIrOATkMD32GiXQfmaVm+DNG96DBhWopHo2hiprRfl/RalYZvtNDJI8K6XNtjsHJqq3t5yyzuoFKp8OsreCn9CYc8ENiJYWMS24omcAFJPPAO79bjMJfmBYWTCtTTf+BuH9buZKlDVUzqIhKJ3pcCxBa2Bz+RuoxqpuK+tWGUi+CEg4VEJ3QM6SUqO3x7G0bSCWFltP57WM7OSi1wT4fHnapHxnZLtfg9vzf6phW6aT5xkOYOA8SFMrkjS839mUZ897hfCGIFpcAlPSHGi3hz/c5yFSiP9gaehFF932X64Md7yshb2opC/cbcyqAb/qOZBAld74=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
